-- AECI-739: the free-text operator note on a vendor claim
-- (STAGE_2_VENDOR_PORTAL_SPEC.md §5.2 step 6). Generated by drizzle-kit, unedited.
-- Purely additive: no CHECK/PK/notnull/type change and no FK on an existing column,
-- so SQLite is not put on the table-recreate path (docs/migrations.md §3.4). That
-- matters here — vendor_requests is the parent of a `duplicate_of_request_id` self-FK
-- and is referenced by workflow_instances, so a recreate would be destructive.
ALTER TABLE `vendor_requests` ADD `admin_notes` text;
