-- AECI-906 — accept `derived` as a fourth `connector_pairs.surface` value.
--
-- The review app now writes 669 rows carrying `derived`: a pair the vendor never
-- published a page for, enumerated from a CLOSED, published connector list. It
-- asserts REACH, not delivery. Without this widening every one of those rows fails
-- the CHECK, and because the connector promote arm commits a whole page in one
-- `db.batch`, ONE such row fails the entire page — a silent no-op sync, not a
-- partial one.
--
-- SQLite has no `ALTER TABLE … ALTER CONSTRAINT`, so widening a CHECK is a full
-- table recreate: `CREATE __new_connector_pairs` → copy → `DROP TABLE` → rename.
-- Generated by drizzle-kit; ONE HAND EDIT applied.
--
--   THE PRAGMA (`docs/migrations.md` §3.3a rule 1). drizzle-kit emits
--   `PRAGMA foreign_keys=OFF` / `=ON`, which is not the lever D1 supports. D1's
--   migrations documentation specifies `PRAGMA defer_foreign_keys = true`, which
--   holds for the surrounding transaction and resets itself on commit — so there is
--   no matching re-enable, and the trailing `=ON` statement is deleted rather than
--   translated. Regenerating this file reintroduces the wrong pragma; re-apply this
--   edit if that happens.
--
-- WHY THIS ONE NEEDS NO HAND-ASSEMBLED STATEMENT ORDER, unlike
-- `0027_powerful_killraven.sql`. In SQLite `DROP TABLE` performs an implicit DELETE
-- that FIRES foreign-key actions, and `defer_foreign_keys` defers violation
-- *reporting*, not cascade *actions* — which is how 0027 would have destroyed 1,697
-- claims had it been left in generated order. That hazard needs a CHILD holding an
-- `ON DELETE CASCADE` FK to the table being dropped. **Nothing references
-- `connector_pairs`.** Its three FKs all point OUTWARD (`connector_catalogs`,
-- `connector_stubs` × 2), and dropping a child fires nothing on its parents. Verify
-- before touching this: `grep -rn "REFERENCES connector_pairs" apps/api/migrations`
-- must stay empty, and no column in `schema.ts` may `.references(() => connectorPairs…)`.
-- If either ever gains a row, this file needs 0027's treatment.
--
--   SUPERSEDED FOR ANY FUTURE RECREATE (2026-09-13, same day). `0033_solid_nightcrawler.sql`
--   (AECI-891) gave `claims` a `connector_pair_id` referencing this table ON DELETE cascade.
--   So the grep above is no longer empty, the containment this file relied on is gone, and
--   the NEXT `connector_pairs` recreate is TWO levels deep — `connector_pairs` → `claims` →
--   `attestations` — which is exactly 0027's shape. Nothing about THIS migration changes; it
--   was safe when it ran. The note exists so the next reader does not inherit a stale
--   all-clear.
--
-- The copy lists all 13 columns explicitly, so `id` (a review-supplied record id, not
-- an autoincrement) carries over verbatim and the promote arm's upsert-by-id keeps
-- matching. `src/test/migration-0032.spec.ts` applies this against seeded rows and
-- asserts they survive (`docs/migrations.md` §3.3a rule 3).
PRAGMA defer_foreign_keys = true;--> statement-breakpoint
CREATE TABLE `__new_connector_pairs` (
	`id` text PRIMARY KEY NOT NULL,
	`catalog_id` text NOT NULL,
	`stub_a_id` text NOT NULL,
	`stub_b_id` text NOT NULL,
	`url_a_to_b` text,
	`url_b_to_a` text,
	`surface` text DEFAULT 'unknown' NOT NULL,
	`classified_at` text,
	`first_seen_at` text NOT NULL,
	`last_seen_at` text NOT NULL,
	`removed_at` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`catalog_id`) REFERENCES `connector_catalogs`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`stub_a_id`) REFERENCES `connector_stubs`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`stub_b_id`) REFERENCES `connector_stubs`(`id`) ON UPDATE no action ON DELETE cascade,
	CONSTRAINT "connector_pairs_canonical_order" CHECK("stub_a_id" < "stub_b_id"),
	CONSTRAINT "connector_pairs_surface_check" CHECK("surface" IN ('curated', 'generated', 'derived', 'unknown'))
);
--> statement-breakpoint
INSERT INTO `__new_connector_pairs`("id", "catalog_id", "stub_a_id", "stub_b_id", "url_a_to_b", "url_b_to_a", "surface", "classified_at", "first_seen_at", "last_seen_at", "removed_at", "created_at", "updated_at") SELECT "id", "catalog_id", "stub_a_id", "stub_b_id", "url_a_to_b", "url_b_to_a", "surface", "classified_at", "first_seen_at", "last_seen_at", "removed_at", "created_at", "updated_at" FROM `connector_pairs`;--> statement-breakpoint
DROP TABLE `connector_pairs`;--> statement-breakpoint
ALTER TABLE `__new_connector_pairs` RENAME TO `connector_pairs`;--> statement-breakpoint
CREATE UNIQUE INDEX `connector_pairs_pair_idx` ON `connector_pairs` (`catalog_id`,`stub_a_id`,`stub_b_id`);--> statement-breakpoint
CREATE INDEX `connector_pairs_stub_b_idx` ON `connector_pairs` (`stub_b_id`);
