-- AECI-1092: contests on connector-evidenced pairs. `integration_field_challenges`
-- gains a second anchor, `evidenced_pair_id`, and `integration_id` becomes nullable,
-- with exactly one of the two set (`integration_field_challenges_anchor_check`, the
-- sum form `claims_anchor_check` uses). `STAGE_2_VENDOR_PORTAL_SPEC.md` §11b.13.
--
-- A TABLE REBUILD, generated by drizzle-kit and then HAND-EDITED in four places.
-- SQLite cannot drop a NOT NULL or add a CHECK in place, so there is no additive
-- form of this change.
--
-- WHY A REBUILD IS SAFE HERE (`docs/migrations.md` §3.3a, the fourth rule). In
-- SQLite `DROP TABLE` performs an implicit DELETE that FIRES foreign-key actions on
-- the tables that reference the dropped one, and `PRAGMA defer_foreign_keys` defers
-- violation reporting, not cascade actions. That hazard needs a CHILD. NOTHING
-- holds a foreign key INTO `integration_field_challenges`: no migration contains
-- `REFERENCES integration_field_challenges`, no `schema.ts` column
-- `.references(() => integrationFieldChallenges…)`, and no table in the 0048
-- snapshot names it in `tableTo`. `src/test/d1.spec.ts` asserts the empty list at
-- HEAD, so a child added later fails CI before the next rebuild can rely on this.
-- Dropping a table that is only a CHILD fires nothing on its parents
-- (`0032_mute_gateway.sql` is the precedent).
--
-- THE FOUR HAND EDITS.
--   1. THE PRAGMA (§3.3a rule 1). drizzle-kit emits `PRAGMA foreign_keys=OFF/ON`,
--      which D1 does not support. `PRAGMA defer_foreign_keys = true` holds for the
--      migration's transaction and resets on commit, so the trailing `=ON` is
--      deleted rather than translated.
--   2. THE COPY (the first failure mode of §0). The generated `INSERT ... SELECT`
--      read `evidenced_pair_id` from the OLD table, which has no such column, so it
--      would have aborted. The copy now lists every old column explicitly, carries
--      the old `integration_id` into the integrations arm, and leaves
--      `evidenced_pair_id` NULL. Every existing contest is an `integrations`
--      contest, so every copied row satisfies the anchor CHECK. `id` is copied
--      verbatim.
--   3. THE PROTEST CHECKS (AECI-1009, migration 0047). `protest_status` and
--      `protest_basis` carry COLUMN-level CHECKs that 0047 wrote by hand and that
--      `schema.ts` deliberately does not declare, so drizzle-kit's generated
--      CREATE TABLE dropped them. They are restored here, byte for byte with the
--      same constraint names. Every other protest column, type, default, FK and
--      `ON DELETE SET NULL` came through the generator unchanged, and so did the
--      `integration_field_challenges_protest_idx` index.
--   4. THIS HEADER.
--
-- The outgoing FKs match 0043 + 0047 exactly (ten), plus the new
-- `evidenced_pair_id -> connector_evidenced_pairs(id) ON DELETE CASCADE`. CASCADE and
-- not SET NULL, because a NULLed anchor would violate the anchor CHECK and so make
-- the parent DELETE fail. This makes the table a cascade child of
-- `connector_evidenced_pairs` too, which `d1.spec.ts` pins.
--
-- `src/test/migration-0049.spec.ts` is the tripwire: it applies this file to a
-- seeded pre-0049 database and asserts every row, including its protest data,
-- survives, that the anchor CHECK holds both ways, and that every index and both
-- protest CHECKs are in the live DDL. Regenerating this file undoes all four edits.
PRAGMA defer_foreign_keys = true;--> statement-breakpoint
CREATE TABLE `__new_integration_field_challenges` (
	`id` text PRIMARY KEY NOT NULL,
	`integration_id` text,
	`evidenced_pair_id` text,
	`field` text NOT NULL,
	`current_value` text,
	`proposed_value` text,
	`reason` text NOT NULL,
	`submitter_vendor_id` text NOT NULL,
	`submitted_by` text,
	`routed_to` text NOT NULL,
	`owner_vendor_id` text,
	`status` text DEFAULT 'open' NOT NULL,
	`decision_note` text,
	`decided_by` text,
	`decided_at` text,
	`upstream_linear_issue_id` text,
	`upstream_linear_issue_url` text,
	`workflow_id` text,
	`protest_status` text CONSTRAINT "integration_field_challenges_protest_status_check" CHECK ("protest_status" IN ('open', 'upheld', 'rejected', 'withdrawn')),
	`protest_basis` text CONSTRAINT "integration_field_challenges_protest_basis_check" CHECK ("protest_basis" IN ('declined', 'silence')),
	`protest_reason` text,
	`protest_evidence` text,
	`protested_by` text,
	`protested_at` text,
	`protest_reply_due_at` text,
	`protest_reply` text,
	`protest_reply_evidence` text,
	`protest_replied_by` text,
	`protest_replied_at` text,
	`protest_decision_note` text,
	`protest_decided_by` text,
	`protest_decided_at` text,
	`protest_workflow_id` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`integration_id`) REFERENCES `integrations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`evidenced_pair_id`) REFERENCES `connector_evidenced_pairs`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`submitter_vendor_id`) REFERENCES `vendors`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`submitted_by`) REFERENCES `profiles`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`owner_vendor_id`) REFERENCES `vendors`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`decided_by`) REFERENCES `profiles`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`workflow_id`) REFERENCES `workflow_instances`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`protested_by`) REFERENCES `profiles`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`protest_replied_by`) REFERENCES `profiles`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`protest_decided_by`) REFERENCES `profiles`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`protest_workflow_id`) REFERENCES `workflow_instances`(`id`) ON UPDATE no action ON DELETE set null,
	CONSTRAINT "integration_field_challenges_field_check" CHECK("field" IN ('name', 'mechanism_kind', 'mechanism_name', 'direction', 'description', 'listing_url', 'docs_url', 'website', 'mechanism_url', 'pricing_model', 'maturity', 'owner')),
	CONSTRAINT "integration_field_challenges_anchor_check" CHECK((("integration_id" IS NOT NULL) + ("evidenced_pair_id" IS NOT NULL)) = 1),
	CONSTRAINT "integration_field_challenges_routed_to_check" CHECK("routed_to" IN ('owner', 'aeci')),
	CONSTRAINT "integration_field_challenges_status_check" CHECK("status" IN ('open', 'accepted', 'declined', 'withdrawn'))
);
--> statement-breakpoint
INSERT INTO `__new_integration_field_challenges`("id", "integration_id", "field", "current_value", "proposed_value", "reason", "submitter_vendor_id", "submitted_by", "routed_to", "owner_vendor_id", "status", "decision_note", "decided_by", "decided_at", "upstream_linear_issue_id", "upstream_linear_issue_url", "workflow_id", "protest_status", "protest_basis", "protest_reason", "protest_evidence", "protested_by", "protested_at", "protest_reply_due_at", "protest_reply", "protest_reply_evidence", "protest_replied_by", "protest_replied_at", "protest_decision_note", "protest_decided_by", "protest_decided_at", "protest_workflow_id", "created_at", "updated_at") SELECT "id", "integration_id", "field", "current_value", "proposed_value", "reason", "submitter_vendor_id", "submitted_by", "routed_to", "owner_vendor_id", "status", "decision_note", "decided_by", "decided_at", "upstream_linear_issue_id", "upstream_linear_issue_url", "workflow_id", "protest_status", "protest_basis", "protest_reason", "protest_evidence", "protested_by", "protested_at", "protest_reply_due_at", "protest_reply", "protest_reply_evidence", "protest_replied_by", "protest_replied_at", "protest_decision_note", "protest_decided_by", "protest_decided_at", "protest_workflow_id", "created_at", "updated_at" FROM `integration_field_challenges`;--> statement-breakpoint
DROP TABLE `integration_field_challenges`;--> statement-breakpoint
ALTER TABLE `__new_integration_field_challenges` RENAME TO `integration_field_challenges`;--> statement-breakpoint
CREATE INDEX `integration_field_challenges_protest_idx` ON `integration_field_challenges` (`protest_status`,`protested_at`) WHERE "protest_status" IS NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX `integration_field_challenges_open_key` ON `integration_field_challenges` (`integration_id`,`field`,`submitter_vendor_id`) WHERE "status" = 'open';--> statement-breakpoint
CREATE UNIQUE INDEX `integration_field_challenges_open_evidenced_key` ON `integration_field_challenges` (`evidenced_pair_id`,`field`,`submitter_vendor_id`) WHERE "status" = 'open' AND "evidenced_pair_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX `integration_field_challenges_owner_idx` ON `integration_field_challenges` (`owner_vendor_id`,`status`);--> statement-breakpoint
CREATE INDEX `integration_field_challenges_queue_idx` ON `integration_field_challenges` (`routed_to`,`status`,`created_at`);--> statement-breakpoint
CREATE INDEX `integration_field_challenges_submitter_idx` ON `integration_field_challenges` (`submitter_vendor_id`,`updated_at`);