/**
 * Machine-readable error codes returned in `ApiError.error.code`. Stable
 * identifiers — messages localize, codes do not. Sourced from the table in
 * docs/API_CONTRACTS.md §4. Keep this in sync with that document.
 */
export const ApiErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  MALFORMED_REQUEST: 'MALFORMED_REQUEST',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  REVIEW_DUPLICATE: 'REVIEW_DUPLICATE',
  REVIEW_BANNED: 'REVIEW_BANNED',
  ENTITLEMENT_REQUIRED: 'ENTITLEMENT_REQUIRED',
  SLUG_CONFLICT: 'SLUG_CONFLICT',
  GRANT_CONFLICT: 'GRANT_CONFLICT',
  CATALOG_VENDOR_MANAGED: 'CATALOG_VENDOR_MANAGED',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  // AECI-1008 integration field contests (`API_CONTRACTS.md` §4).
  CONTEST_OWN_INTEGRATION: 'CONTEST_OWN_INTEGRATION',
  CONTEST_DUPLICATE: 'CONTEST_DUPLICATE',
  CONTEST_NOT_OPEN: 'CONTEST_NOT_OPEN',
  CONTEST_ROUTED_TO_OWNER: 'CONTEST_ROUTED_TO_OWNER',
  CONTEST_NO_CHANGE: 'CONTEST_NO_CHANGE',
  CONTEST_INVALID_VALUE: 'CONTEST_INVALID_VALUE',
  RATE_LIMITED: 'RATE_LIMITED',
  DEPENDENCY_FAILURE: 'DEPENDENCY_FAILURE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ApiErrorCode = (typeof ApiErrorCode)[keyof typeof ApiErrorCode];
