-- `trade` controlled vocabulary for Cloudflare D1 (AECI-538 epic / AECI-540).
-- Canonical seed + source of truth for the main-app `taxonomy_trades` table, mirroring
-- apps/api/seed/data-objects.sql. Materialises the closed 34-term vocabulary from
-- docs/TRADES_VOCABULARY.md (§5) / its generated mirror docs/trades-vocabulary.json.
--
-- Idempotent UPSERTs keyed on slug; ids are deterministic UUIDv5(slug) so they are stable
-- across re-runs and environments. Applied with `pnpm db:seed:trades:local` →
-- `wrangler d1 execute aeci-app-<env> --file=seed/trades.sql` (and the per-env --remote
-- seed step in scripts/d1-apply-migrations.sh). NEVER deletes — a delete would cascade to
-- product_trades. Writes taxonomy_trades ONLY; product_trades rows come from the promote
-- flow (AECI-542), never from this seed (ADR 0008).
--
-- `description` is seeded NON-NULL for every term (the column is `not null`): /trades/:slug
-- ships as an SEO landing page, so copy is part of the contract. `aliases` is a JSON array,
-- dual-purpose (TRADES_VOCABULARY.md §4): the promote ingest resolves an incoming trade
-- find-only by slug → name → alias (never find-or-create), AND AECI-545 indexes the aliases
-- as searchable-only Algolia content so "blacktop"/"glazier" reach the right products.
--
-- UUIDv5 namespace = UUIDv5(URL_NS, 'https://aecintegrations.com/vocabulary/trade')
--                  = af0d33bc-5814-524f-9c6c-cac49b84d5f0
-- (URL_NS = 6ba7b811-9dad-11d1-80b4-00c04fd430c8, RFC 9562 §6.6). Ids are not stored in the
-- doc or the JSON mirror — they are derived from the slug. This is the same construction
-- data-objects.sql uses, one vocabulary path along; `uuidv5(slug, NAMESPACE)` in any RFC
-- 9562 implementation reproduces a row's id. The executable reference is `uuidv5()` in
-- src/test/d1.spec.ts, which re-derives all 34 ids and asserts they match this file.
--
-- Edit the doc table + the JSON mirror, then regenerate this file — never hand-edit rows
-- (the d1.spec drift test asserts every id/name/description/display_order/alias matches).

INSERT INTO "taxonomy_trades" ("id","slug","name","description","display_order","aliases","created_at","updated_at") VALUES
  ('3ef5f178-d19e-5cc0-8041-9bef758be94e', 'concrete', 'Concrete', 'Cast-in-place concrete: formwork, placing, finishing, and flatwork.', 10, '["Cast-in-Place","Cast in Place Concrete","Formwork","Flatwork","Poured Concrete","Concrete Contracting","Tilt-Up"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('4cf8dc3f-8cca-5f3a-a611-9b36db87b174', 'crane-rigging', 'Crane & Rigging', 'Crane operations, lift planning, hoisting, and heavy rigging.', 20, '["Crane","Cranes","Rigging","Lift Planning","Hoisting","Heavy Haul","Crane & Hoisting"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('b4aa0aa3-e90d-5fae-878f-22a359821ee8', 'deep-foundations', 'Deep Foundations & Piling', 'Piles, drilled shafts, caissons, ground improvement, and earth retention.', 30, '["Piling","Piles","Pile Driving","Drilled Shafts","Caissons","Earth Retention","Shoring & Piling","Ground Improvement"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('9b164a6b-c087-5c17-8e0b-049272cf5867', 'demolition', 'Demolition', 'Structural and selective interior demolition, including deconstruction.', 40, '["Demo","Selective Demolition","Interior Demolition","Deconstruction","Wrecking"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('7730395f-af5f-5857-b3d6-afe798c18957', 'doors-frames-hardware', 'Doors, Frames & Hardware', 'Door and frame supply, finish hardware scheduling, and openings installation.', 50, '["Doors & Hardware","Door Hardware","Finish Hardware","Openings","Hollow Metal","DHI"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('9073e4a4-72dc-50ea-89ad-641aa970af36', 'drywall-interior-framing', 'Drywall & Interior Framing', 'Metal stud framing, gypsum board, taping, finishing, and acoustical ceilings.', 60, '["Drywall","Gypsum","Interior Framing","Metal Stud Framing","Taping","Wall & Ceiling","Acoustical Ceilings","ACT"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('dd07a6e1-cbe6-5c94-89b7-37fad40729af', 'earthwork-excavation', 'Earthwork & Excavation', 'Excavation, grading, mass haul, and soil work on the site.', 70, '["Excavation","Grading","Earthmoving","Dirt Work","Mass Haul","Site Grading","Excavating"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('65946241-7536-59e5-bb8d-9d5518236b37', 'electrical', 'Electrical', 'Power distribution, lighting, and electrical systems installation.', 80, '["Electric","Electrical Contracting","Electrician","Power","Lighting Installation","Electrical Trade"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('f49f622a-75f0-52b9-bde7-252a76a6366a', 'elevators-conveying', 'Elevators & Conveying', 'Elevators, escalators, lifts, and other vertical transportation systems.', 90, '["Elevator","Elevators","Vertical Transportation","Escalators","Lifts","Conveying Systems"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('b390c5de-fb06-5ebd-9f2b-48d669c68fd9', 'environmental-abatement', 'Environmental & Abatement', 'Asbestos, lead, and mold abatement plus environmental remediation.', 100, '["Abatement","Asbestos Abatement","Asbestos","Lead Abatement","Mold Remediation","Remediation","Hazmat","Environmental"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('87610811-6222-5083-a4d3-42b5b1e7a99d', 'fire-protection', 'Fire Protection', 'Fire sprinkler, standpipe, and suppression system design and installation.', 110, '["Fire Sprinkler","Sprinkler","Sprinklers","Fire Suppression","Suppression","Fire Life Safety","Fire Protection Contracting"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('9d87957b-c89c-50f0-b11c-f4aace6c872d', 'fireproofing-firestopping', 'Fireproofing & Firestopping', 'Applied fireproofing and through-penetration firestopping.', 120, '["Fireproofing","Firestopping","Spray Fireproofing","Intumescent","Penetration Firestop"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('dbacfc1c-9499-5947-b96a-e5ff8fab0977', 'flooring', 'Flooring', 'Resilient, carpet, wood, and polished-concrete floor covering.', 130, '["Floor Covering","Floorcovering","Carpet","Resilient Flooring","Hardwood","Polished Concrete","Flooring Contracting"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('56c229aa-bac9-531f-bcbe-20f019a96c7a', 'framing-carpentry', 'Framing & Carpentry', 'Wood and light-gauge structural framing plus rough and finish carpentry.', 140, '["Carpentry","Wood Framing","Light Gauge Steel Framing","LGS","Rough Carpentry","Finish Carpentry","Trusses","Framing"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('dfd60958-23ef-50ee-af5c-5807bedff269', 'glazing-curtain-wall', 'Glazing & Curtain Wall', 'Glass, storefront, curtain wall, and window-wall fabrication and installation.', 150, '["Glass","Glazing","Glazier","Curtain Wall","Storefront","Window Wall","Fenestration","Glass & Glazing"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('d859c620-c555-5167-be4e-c4ddd3441787', 'hvac-mechanical', 'HVAC & Mechanical', 'Heating, ventilation, air conditioning, hydronics, and process piping.', 160, '["HVAC","Mechanical","Mechanical Contracting","Air Conditioning","Heating & Cooling","Hydronics","Process Piping","Mechanical Trade"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('1fa12a27-867c-55f3-aadc-6ec21808daa7', 'insulation', 'Insulation', 'Building-envelope and mechanical insulation, including spray foam.', 170, '["Mechanical Insulation","Thermal Insulation","Building Insulation","Spray Foam","Pipe Insulation"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('378ebfe6-0d74-52cc-bf25-91a33ec454fa', 'landscaping-irrigation', 'Landscaping & Irrigation', 'Planting, hardscape, irrigation, and grounds maintenance.', 180, '["Landscape","Landscaping","Irrigation","Hardscape","Grounds Maintenance","Green Industry","Lawn Care"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('b7dd6da5-f69a-5cab-83c8-a4b14387ef3d', 'low-voltage-security', 'Low Voltage & Security', 'Structured cabling, access control, surveillance, AV, and building networks.', 190, '["Low Voltage","Security Systems","Access Control","Surveillance","AV","Audio Visual","Structured Cabling","Systems Integration","Alarm","Fire Alarm"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('39647ed7-917b-57f8-b020-54c9b2080259', 'masonry', 'Masonry', 'Brick, block, stone, and cast-stone construction.', 200, '["Brick","Bricklaying","Block","CMU","Stone","Cast Stone","Masonry Contracting"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('dc6b4365-a326-5f40-87c5-eae5d8d61211', 'millwork-casework', 'Millwork & Casework', 'Architectural woodwork, casework, cabinetry, and countertops.', 210, '["Millwork","Casework","Cabinetry","Cabinets","Architectural Woodwork","Cabinet Shop","Countertops","AWI"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('11187b70-e382-5538-98bc-7736c25af1d3', 'painting-coatings', 'Painting & Coatings', 'Architectural painting, industrial coatings, and wall covering.', 220, '["Painting","Painter","Coatings","Industrial Coatings","Wallcovering","Wall Covering","Painting & Decorating"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('b9a6deff-46e6-56f9-8d46-68a9764da2a7', 'paving-asphalt', 'Paving & Asphalt', 'Asphalt and concrete paving, striping, sealcoating, and pavement maintenance.', 230, '["Paving","Asphalt","Pavement","Blacktop","Striping","Sealcoating","Pavement Maintenance","Asphalt Paving"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('91e8fd78-bd62-5f18-9d74-e07e6471f736', 'plumbing', 'Plumbing', 'Domestic water, sanitary, medical gas, and fuel-gas piping systems.', 240, '["Plumber","Plumbing Contracting","Sanitary","Domestic Water","Med Gas","Medical Gas","Plumbing Trade"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('47abc414-84d1-53f1-8854-00096afc977f', 'precast-concrete', 'Precast Concrete', 'Plant-cast structural and architectural precast, including erection.', 250, '["Precast","Architectural Precast","Structural Precast","Hollowcore","Double Tee"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('73cd717f-43cf-5ffc-a087-e461c377979e', 'rebar-reinforcing', 'Rebar & Reinforcing Steel', 'Reinforcing steel detailing, fabrication, and placement, including post-tensioning.', 260, '["Rebar","Reinforcing Steel","Reinforcement","Rebar Detailing","Post-Tensioning","PT","Rod Busting"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('a1e595e7-4b34-5180-b4d6-72cbed999bd1', 'restoration-waterproofing', 'Restoration & Waterproofing', 'Building-envelope restoration, waterproofing, sealants, and caulking.', 270, '["Waterproofing","Sealants","Caulking","Building Envelope","Facade Restoration","Tuckpointing","Concrete Restoration"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('2e70e0ab-7d6d-5626-a937-4179efa842f2', 'roofing', 'Roofing', 'Low-slope and steep-slope roof systems, repair, and replacement.', 280, '["Roofer","Roof","Roofing Contracting","Commercial Roofing","Residential Roofing","Re-Roofing","Roof Replacement","Sheet Roofing"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('d7f159d2-0b4a-5547-bdda-a4b45b32315e', 'scaffolding-access', 'Scaffolding & Access', 'Scaffold, shoring, swing stage, and temporary access systems.', 290, '["Scaffold","Scaffolding","Shoring","Swing Stage","Suspended Access","Access Equipment","Formwork & Shoring"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('348693dc-7a62-5556-a646-ffdae54389a8', 'sheet-metal', 'Sheet Metal', 'Duct fabrication and installation plus architectural sheet metal.', 300, '["Ductwork","Duct","Duct Fabrication","HVAC Sheet Metal","Architectural Sheet Metal","Fab Shop","SMACNA"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('d084dd51-0122-5048-bd8b-b9278eca5998', 'sitework-utilities', 'Sitework & Underground Utilities', 'Wet and dry underground utilities, storm, sewer, and site infrastructure.', 310, '["Underground Utilities","Utilities","Site Utilities","Wet Utilities","Dry Utilities","Storm Drain","Sewer","Underground"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('e720f514-3fab-5a8f-b4b8-36006335b06a', 'solar-renewables', 'Solar & Renewables', 'Solar PV, battery storage, EV charging, and renewable-energy installation.', 320, '["Solar","PV","Photovoltaic","Solar Installation","Renewable Energy","Battery Storage","Energy Storage","EV Charging"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('1480fb07-e1ab-52de-8bf1-eeb093c590a0', 'structural-steel', 'Structural Steel & Metals', 'Structural steel detailing, fabrication, erection, and miscellaneous metals.', 330, '["Structural Steel","Steel","Steel Erection","Steel Fabrication","Ironworker","Misc Metals","Miscellaneous Metals","Ornamental Metals","Metal Fabrication"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('be231688-b7a2-5812-8518-6c1af714a562', 'tile-stone', 'Tile & Stone', 'Ceramic tile, natural stone, and terrazzo setting.', 340, '["Tile","Tile Setting","Ceramic Tile","Stone Setting","Terrazzo","Tilework"]', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'))
ON CONFLICT ("slug") DO UPDATE SET
  "name" = excluded."name",
  "description" = excluded."description",
  "display_order" = excluded."display_order",
  "aliases" = excluded."aliases",
  "updated_at" = strftime('%Y-%m-%dT%H:%M:%fZ','now');
