export interface LinkRef {
  id: string;
  name: string;
}

export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  offset: number;
  limit: number;
}

export type PromotionStatus = 'pending' | 'ready' | 'promoted' | 'retracted' | 'rejected';

/** One discipline / phase entry in the usefulness payload. */
export interface ProductUsefulnessEntry {
  id: string;
  name: string;
  points: string[];
}

/**
 * "How would each discipline / phase use this product?" — generated by the
 * research workflow alongside the discipline/phase link assignments. Each
 * entry's `id` matches one of the product's `disciplines[]` / `phases[]`
 * record IDs; the UI filters out stale entries client-side when a curator
 * removes a link.
 */
export interface ProductUsefulness {
  disciplines: ProductUsefulnessEntry[];
  phases: ProductUsefulnessEntry[];
}

export interface Product {
  id: string;
  name: string;
  website?: string;
  description?: string;
  categories: LinkRef[];
  vendors: LinkRef[];
  disciplines: LinkRef[];
  phases: LinkRef[];
  usefulness?: ProductUsefulness;
  researchStatus?: string;
  promotionStatus?: PromotionStatus;
  integrationCount: number;

  // Enrichment signals
  hasApiDocs?: boolean;
  apiDocsUrl?: string;
  toolIntegrationsUrl?: string;
  sourceMarketplaces?: string[];
  marketplaceCount?: number;
  ipaasPlatforms?: string[];
  ipaasCount?: number;
  zapierUrl?: string;
  makeUrl?: string;
  workatoUrl?: string;

  // Market signals
  g2ReviewCount?: number;
  g2Rating?: number;
  g2Url?: string;
  capterraReviewCount?: number;
  capterraRating?: number;
  capterraUrl?: string;
  searchVolumeMonthly?: number;
  googleTrendsIndex?: number;
  redditMentions24mo?: number;

  // Scoring
  integrationScore?: number;
  demandScore?: number;
  /** @deprecated Removed when priority moved to a 2-pillar model. Hydrated for historical Airtable values only. */
  outreachScore?: number;
  priorityScore?: number;
  priorityTier?: string;
  priorityConfidence?: string;
  priorityFlags?: string[];
  emergingFlag?: boolean;
  toolDataCompleteness?: number;
  toolEnrichmentStatus?: string;
  lastToolEnrichedAt?: string;
  lastScoredAt?: string;

  // Linked vendor's VQS — surfaced beside priority. NOT multiplied into the
  // priority score; the vendor outreach concern lives in VQS at the vendor
  // table.
  vendorVqsScore?: number;
  vendorVqsTier?: string;
}

export interface ProductDetail extends Product {
  researchNotes?: string;
  toolIntegrationCheckNotes?: string;
  toolIntegrationCheckedAt?: string;
  adminNotes?: string;
  integrationsAsSource: IntegrationSummary[];
  integrationsAsTarget: IntegrationSummary[];
  integratedProducts: IntegratedProductSummary[];
  integrationsDiscoveryCheckedAt?: string;
  integrationsDiscoverySummary?: string;
  integrationsDiscoveryCandidates?: UnresolvedIntegrationCandidate[];
}

export interface UnresolvedIntegrationCandidate {
  targetName: string;
  targetWebsite?: string;
  targetVendorName?: string;
  mechanismKind?: string;
  mechanismName?: string;
  direction?: 'one-way' | 'bidirectional';
  evidenceUrl: string;
  evidenceSource: 'website' | 'ipaas' | 'marketplaces' | 'g2' | 'github' | 'web';
  notes?: string;
  confidence: 'high' | 'medium' | 'low';
}

export interface IntegrationSummary {
  id: string;
  name: string;
  sourceProduct?: LinkRef;
  targetProduct?: LinkRef;
  integrationType?: string;
  description?: string;
  direction?: string;
  mechanismKind?: string;
  poweredByProduct?: LinkRef;
  mechanismName?: string;
  mechanismUrl?: string;
  website?: string;
  docsUrl?: string;
  listingUrl?: string;
  builtBy?: LinkRef;
  pricingModel?: string;
  maturity?: string;
  notes?: string;
}

export interface IntegratedProductSummary {
  id: string;
  name: string;
  website?: string;
  vendors: LinkRef[];
  categories: LinkRef[];
  researchStatus?: string;
  priorityTier?: string;
  priorityScore?: number;
  integrationCount: number;
  integrationIds: string[];
}

export interface Vendor {
  id: string;
  companyName: string;
  website?: string;
  headquarters?: string;
  foundedYear?: number;
  companySize?: string;
  publicPrivate?: string;
  parentCompany?: string;
  logoUrl?: string;
  toolCount: number;

  fundingStage?: string;
  githubStarsTotal?: number;
  vendorEnrichmentStatus?: string;
  vendorDataCompleteness?: number;

  vqsScore?: number;
  vqsTier?: string;
  vqsConfidence?: string;
}

export interface VendorDetail extends Vendor {
  description?: string;
  linkedinUrl?: string;
  crunchbaseUrl?: string;
  wikiUrl?: string;
  sourceUrl?: string;
  phoneNumber?: string;
  contactEmail?: string;
  tools: LinkRef[];

  githubOrg?: string;
  githubOrgVerified?: boolean;
  githubRepoCount?: number;
  hasSdkRepo?: boolean;
  githubLastCommitDaysAgo?: number;
  githubCheckedAt?: string;

  fundingCheckedAt?: string;

  crunchbaseRank?: number;
  crunchbaseGrowthScore?: number;
  crunchbaseHeatScore?: number;
  crunchbaseCategories?: string[];
  monthlyWebVisits?: number;
  crunchbaseLists?: CrunchbaseList[];
  crunchbaseCheckedAt?: string;

  vqsCredibility?: number;
  vqsMomentum?: number;
  vqsFit?: number;
  vqsFlags?: string[];

  lastEnrichedAt?: string;

  adminNotes?: string;
}

export interface CrunchbaseList {
  name: string;
  countOrgs?: number;
  totalFunding?: string;
  countInvestors?: number;
}

export interface MetaResponse {
  categories: LinkRef[];
  disciplines: LinkRef[];
  phases: LinkRef[];
  vendors: LinkRef[];
  researchStatuses: string[];
  priorityTiers: string[];
  toolEnrichmentStatuses: string[];
}

export interface StatsResponse {
  integrations: { total: number };
  vendors: {
    total: number;
    byStatus: Record<string, number>;
    byTier: Record<string, number>;
    tierBuckets: { key: string; label: string }[];
  };
  tools: {
    total: number;
    byResearchStatus: Record<string, number>;
    byPriority: Record<string, number>;
  };
}

// ---------------------------------------------------------------------------
// Write payloads (mirror server/types.ts)
// ---------------------------------------------------------------------------
export interface CreateProductRequest {
  name: string;
  description?: string;
  website?: string;
  model?: string;
  forceRefresh?: boolean;
  skipOrchestrator?: boolean;
}

export interface CreateProductResponse {
  product: Product;
  run?: { runId: string; workflow: string; model: string };
}

export interface CreateVendorRequest {
  companyName: string;
  website?: string;
  description?: string;
  model?: string;
  forceRefresh?: boolean;
  skipOrchestrator?: boolean;
}

export interface CreateVendorResponse {
  vendor: { recordId: string };
  run?: { runId: string; workflow: string; model: string };
}

export interface UpdateProductRequest {
  name?: string;
  description?: string;
  website?: string;
  toolIntegrationsUrl?: string;
  apiDocsUrl?: string;
  hasApiDocs?: boolean;
  researchStatus?: string;
  promotionStatus?: PromotionStatus;
  researchNotes?: string;
  toolIntegrationCheckNotes?: string;
  adminNotes?: string;
  categories?: string[];
  disciplines?: string[];
  phases?: string[];
  vendors?: string[];
}

export interface UpdateVendorRequest {
  companyName?: string;
  description?: string;
  website?: string;
  headquarters?: string;
  foundedYear?: number | null;
  publicPrivate?: string | null;
  parentCompany?: string;
  linkedinUrl?: string;
  crunchbaseUrl?: string;
  wikiUrl?: string;
  sourceUrl?: string;
  githubOrg?: string;
  phoneNumber?: string;
  contactEmail?: string;
  adminNotes?: string;
}

/** One playbook returned by GET /api/playbooks. Body is the full markdown
 *  ready for clipboard, sans frontmatter. `scope_label === null` opts out
 *  of the per-card scope textarea on the /prompts page. */
export interface PlaybookSummary {
  slug: string;
  title: string;
  description: string;
  scope_label: string | null;
  scope_placeholder: string | null;
  body: string;
}
